// <auto-generated />
using System;
using CondominusApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondominusApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231203181019_Models")]
    partial class Models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CondominusApi.Models.Apartamento", b =>
                {
                    b.Property<int>("IdApart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApart"));

                    b.Property<int?>("CondominioApartIdCond")
                        .HasColumnType("int");

                    b.Property<int>("IdCondominioApart")
                        .HasColumnType("int");

                    b.Property<string>("NumeroApart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneApart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdApart");

                    b.HasIndex("CondominioApartIdCond");

                    b.ToTable("Apartamentos");

                    b.HasData(
                        new
                        {
                            IdApart = 1,
                            IdCondominioApart = 1,
                            NumeroApart = "A001",
                            TelefoneApart = "11912345678"
                        },
                        new
                        {
                            IdApart = 2,
                            IdCondominioApart = 1,
                            NumeroApart = "B002",
                            TelefoneApart = "11912345678"
                        },
                        new
                        {
                            IdApart = 3,
                            IdCondominioApart = 1,
                            NumeroApart = "C003",
                            TelefoneApart = "11887654321"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.AreaComum", b =>
                {
                    b.Property<int>("IdAreaComum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAreaComum"));

                    b.Property<string>("NomeAreaComum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAreaComum");

                    b.ToTable("AreasComuns");

                    b.HasData(
                        new
                        {
                            IdAreaComum = 1,
                            NomeAreaComum = "Churrasqueira"
                        },
                        new
                        {
                            IdAreaComum = 2,
                            NomeAreaComum = "Salão de Jogos"
                        },
                        new
                        {
                            IdAreaComum = 3,
                            NomeAreaComum = "Quadra"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Condominio", b =>
                {
                    b.Property<int>("IdCond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCond"));

                    b.Property<string>("EnderecoCond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCond")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCond");

                    b.ToTable("Condominios");

                    b.HasData(
                        new
                        {
                            IdCond = 1,
                            EnderecoCond = "Rua Guaranésia, 1070",
                            NomeCond = "Vila Nova Maria"
                        },
                        new
                        {
                            IdCond = 2,
                            EnderecoCond = "Rua Paulo Andrighetti, 1573",
                            NomeCond = "Condomínio Aquarella Pari Colore"
                        },
                        new
                        {
                            IdCond = 3,
                            EnderecoCond = "Rua Paulo Andrighetti, 449",
                            NomeCond = "Condomínio Edifício Antônio Walter Santiago"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Dependente", b =>
                {
                    b.Property<int>("IdDependente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDependente"));

                    b.Property<string>("CpfDependente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPessoaDependente")
                        .HasColumnType("int");

                    b.Property<string>("NomeDependente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaDependenteIdPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdDependente");

                    b.HasIndex("PessoaDependenteIdPessoa");

                    b.ToTable("Dependentes");

                    b.HasData(
                        new
                        {
                            IdDependente = 1,
                            CpfDependente = "11242100083",
                            IdPessoaDependente = 1,
                            NomeDependente = "João Gomes"
                        },
                        new
                        {
                            IdDependente = 2,
                            CpfDependente = "30777454025",
                            IdPessoaDependente = 1,
                            NomeDependente = "Maria Silva"
                        },
                        new
                        {
                            IdDependente = 3,
                            CpfDependente = "53086593032",
                            IdPessoaDependente = 2,
                            NomeDependente = "Carlos Oliveira"
                        },
                        new
                        {
                            IdDependente = 4,
                            CpfDependente = "54710630070",
                            IdPessoaDependente = 3,
                            NomeDependente = "Ana Souza"
                        },
                        new
                        {
                            IdDependente = 5,
                            CpfDependente = "03940474002",
                            IdPessoaDependente = 3,
                            NomeDependente = "Pedro Santos"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Entrega", b =>
                {
                    b.Property<int>("IdEnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnt"));

                    b.Property<int?>("ApartamentoEntIdApart")
                        .HasColumnType("int");

                    b.Property<string>("CodEnt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEntregaEnt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetiradaEnt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinatarioEnt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdApartamentoEnt")
                        .HasColumnType("int");

                    b.HasKey("IdEnt");

                    b.HasIndex("ApartamentoEntIdApart");

                    b.ToTable("Entregas");

                    b.HasData(
                        new
                        {
                            IdEnt = 1,
                            CodEnt = "NBR1354897",
                            DataEntregaEnt = new DateTime(2023, 12, 3, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1854),
                            DataRetiradaEnt = new DateTime(2023, 12, 4, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1869),
                            DestinatarioEnt = "Joao Guilherme",
                            IdApartamentoEnt = 1
                        },
                        new
                        {
                            IdEnt = 2,
                            CodEnt = "NBR2468135",
                            DataEntregaEnt = new DateTime(2023, 12, 3, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1876),
                            DataRetiradaEnt = new DateTime(2023, 12, 5, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1877),
                            DestinatarioEnt = "Maria Joaquina",
                            IdApartamentoEnt = 2
                        },
                        new
                        {
                            IdEnt = 3,
                            CodEnt = "NBR3581415",
                            DataEntregaEnt = new DateTime(2023, 12, 3, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1879),
                            DataRetiradaEnt = new DateTime(2023, 12, 4, 15, 10, 19, 154, DateTimeKind.Local).AddTicks(1879),
                            DestinatarioEnt = "Ana Clara",
                            IdApartamentoEnt = 3
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacao"));

                    b.Property<string>("AssuntoNotificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvioNotificacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPessoaNotificacao")
                        .HasColumnType("int");

                    b.Property<string>("MensagemNotificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaNotificacaoIdPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("PessoaNotificacaoIdPessoa");

                    b.ToTable("Notificacoes");

                    b.HasData(
                        new
                        {
                            IdNotificacao = 1,
                            AssuntoNotificacao = "Manutenção elétrica",
                            DataEnvioNotificacao = new DateTime(2023, 12, 6, 9, 13, 22, 0, DateTimeKind.Unspecified),
                            IdPessoaNotificacao = 0,
                            MensagemNotificacao = "Haverá manutencão no quadro de força do prédio, dia: 20/12 as 14 horas"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<int?>("ApartamentoPessoaIdApart")
                        .HasColumnType("int");

                    b.Property<string>("CpfPessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdApartamentoPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioPessoa")
                        .HasColumnType("int");

                    b.Property<string>("NomePessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonePessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPessoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPessoa");

                    b.HasIndex("ApartamentoPessoaIdApart");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            IdPessoa = 1,
                            CpfPessoa = "56751898901",
                            IdApartamentoPessoa = 1,
                            NomePessoa = "João Gomes",
                            TelefonePessoa = "11924316523",
                            TipoPessoa = "Sindico"
                        },
                        new
                        {
                            IdPessoa = 2,
                            CpfPessoa = "89674156892",
                            IdApartamentoPessoa = 2,
                            NomePessoa = "Maria Oliveira",
                            TelefonePessoa = "1198254351",
                            TipoPessoa = "Morador"
                        },
                        new
                        {
                            IdPessoa = 3,
                            CpfPessoa = "32569874561",
                            IdApartamentoPessoa = 3,
                            NomePessoa = "João Viana",
                            TelefonePessoa = "11984512345",
                            TipoPessoa = "Morador"
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.PessoaAreaComum", b =>
                {
                    b.Property<int>("IdPessoaPessArea")
                        .HasColumnType("int");

                    b.Property<int>("IdAreaComumPessArea")
                        .HasColumnType("int");

                    b.Property<int?>("AreaComumPessAreaIdAreaComum")
                        .HasColumnType("int");

                    b.Property<int>("IdPessArea")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaPessAreaIdPessoa")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataHoraFimPessArea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataHoraInicioPessArea")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPessoaPessArea", "IdAreaComumPessArea");

                    b.HasIndex("AreaComumPessAreaIdAreaComum");

                    b.HasIndex("PessoaPessAreaIdPessoa");

                    b.ToTable("PessoasAreasComuns");

                    b.HasData(
                        new
                        {
                            IdPessoaPessArea = 1,
                            IdAreaComumPessArea = 1,
                            IdPessArea = 1,
                            dataHoraFimPessArea = new DateTime(2023, 12, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            dataHoraInicioPessArea = new DateTime(2023, 12, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdPessoaPessArea = 2,
                            IdAreaComumPessArea = 1,
                            IdPessArea = 2,
                            dataHoraFimPessArea = new DateTime(2023, 12, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            dataHoraInicioPessArea = new DateTime(2023, 12, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdPessoaPessArea = 2,
                            IdAreaComumPessArea = 2,
                            IdPessArea = 2,
                            dataHoraFimPessArea = new DateTime(2023, 12, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            dataHoraInicioPessArea = new DateTime(2023, 12, 16, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.PessoaNoti", b =>
                {
                    b.Property<int>("IdPessoaPessoaNoti")
                        .HasColumnType("int");

                    b.Property<int>("IdNotificacaoPessoaNoti")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoaNoti")
                        .HasColumnType("int");

                    b.Property<int?>("NotificacaoPessoaNotiIdNotificacao")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaPessoaNotiIdPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdPessoaPessoaNoti", "IdNotificacaoPessoaNoti");

                    b.HasIndex("NotificacaoPessoaNotiIdNotificacao");

                    b.HasIndex("PessoaPessoaNotiIdPessoa");

                    b.ToTable("PessoaNotis");

                    b.HasData(
                        new
                        {
                            IdPessoaPessoaNoti = 1,
                            IdNotificacaoPessoaNoti = 1,
                            IdPessoaNoti = 1
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAcessoUsuario")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPessoaUsuario")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHashUsuario")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSaltUsuario")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            EmailUsuario = "admin@gmail.com",
                            IdPessoaUsuario = 1,
                            PasswordHashUsuario = new byte[] { 76, 82, 99, 239, 101, 0, 118, 171, 229, 114, 129, 203, 22, 70, 225, 171, 22, 195, 70, 62, 198, 140, 184, 216, 190, 150, 80, 186, 20, 198, 104, 227, 161, 221, 244, 222, 3, 155, 227, 50, 123, 89, 16, 197, 17, 235, 166, 102, 90, 56, 47, 84, 151, 121, 141, 172, 224, 26, 19, 25, 71, 141, 163, 110 },
                            PasswordSaltUsuario = new byte[] { 33, 237, 141, 147, 206, 176, 46, 83, 186, 126, 77, 143, 127, 105, 48, 15, 94, 45, 132, 245, 248, 226, 141, 223, 81, 34, 120, 223, 105, 220, 139, 188, 190, 161, 239, 198, 62, 133, 155, 48, 238, 247, 230, 223, 140, 246, 179, 215, 209, 89, 97, 68, 109, 33, 148, 146, 251, 195, 116, 63, 192, 220, 72, 186, 235, 144, 87, 73, 59, 226, 79, 28, 49, 227, 163, 211, 95, 172, 126, 21, 7, 82, 128, 142, 199, 192, 222, 177, 244, 145, 151, 227, 89, 110, 130, 63, 64, 167, 124, 124, 32, 114, 10, 168, 236, 152, 42, 199, 252, 32, 38, 148, 140, 36, 132, 224, 166, 171, 181, 131, 145, 250, 238, 95, 227, 34, 197, 210 }
                        });
                });

            modelBuilder.Entity("CondominusApi.Models.Apartamento", b =>
                {
                    b.HasOne("CondominusApi.Models.Condominio", "CondominioApart")
                        .WithMany("ApartamentosCond")
                        .HasForeignKey("CondominioApartIdCond");

                    b.Navigation("CondominioApart");
                });

            modelBuilder.Entity("CondominusApi.Models.Dependente", b =>
                {
                    b.HasOne("CondominusApi.Models.Pessoa", "PessoaDependente")
                        .WithMany("DependentesPessoa")
                        .HasForeignKey("PessoaDependenteIdPessoa");

                    b.Navigation("PessoaDependente");
                });

            modelBuilder.Entity("CondominusApi.Models.Entrega", b =>
                {
                    b.HasOne("CondominusApi.Models.Apartamento", "ApartamentoEnt")
                        .WithMany("EntregasApart")
                        .HasForeignKey("ApartamentoEntIdApart");

                    b.Navigation("ApartamentoEnt");
                });

            modelBuilder.Entity("CondominusApi.Models.Notificacao", b =>
                {
                    b.HasOne("CondominusApi.Models.Pessoa", "PessoaNotificacao")
                        .WithMany()
                        .HasForeignKey("PessoaNotificacaoIdPessoa");

                    b.Navigation("PessoaNotificacao");
                });

            modelBuilder.Entity("CondominusApi.Models.Pessoa", b =>
                {
                    b.HasOne("CondominusApi.Models.Apartamento", "ApartamentoPessoa")
                        .WithMany("PessoasApart")
                        .HasForeignKey("ApartamentoPessoaIdApart");

                    b.Navigation("ApartamentoPessoa");
                });

            modelBuilder.Entity("CondominusApi.Models.PessoaAreaComum", b =>
                {
                    b.HasOne("CondominusApi.Models.AreaComum", "AreaComumPessArea")
                        .WithMany("PessoaACAreaComum")
                        .HasForeignKey("AreaComumPessAreaIdAreaComum");

                    b.HasOne("CondominusApi.Models.Pessoa", "PessoaPessArea")
                        .WithMany("PessoaACPessoa")
                        .HasForeignKey("PessoaPessAreaIdPessoa");

                    b.Navigation("AreaComumPessArea");

                    b.Navigation("PessoaPessArea");
                });

            modelBuilder.Entity("CondominusApi.Models.PessoaNoti", b =>
                {
                    b.HasOne("CondominusApi.Models.Notificacao", "NotificacaoPessoaNoti")
                        .WithMany()
                        .HasForeignKey("NotificacaoPessoaNotiIdNotificacao");

                    b.HasOne("CondominusApi.Models.Pessoa", "PessoaPessoaNoti")
                        .WithMany("PessoaNotiPessoa")
                        .HasForeignKey("PessoaPessoaNotiIdPessoa");

                    b.Navigation("NotificacaoPessoaNoti");

                    b.Navigation("PessoaPessoaNoti");
                });

            modelBuilder.Entity("CondominusApi.Models.Usuario", b =>
                {
                    b.HasOne("CondominusApi.Models.Pessoa", "PessoaUsuario")
                        .WithOne("UsuarioPessoa")
                        .HasForeignKey("CondominusApi.Models.Usuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PessoaUsuario");
                });

            modelBuilder.Entity("CondominusApi.Models.Apartamento", b =>
                {
                    b.Navigation("EntregasApart");

                    b.Navigation("PessoasApart");
                });

            modelBuilder.Entity("CondominusApi.Models.AreaComum", b =>
                {
                    b.Navigation("PessoaACAreaComum");
                });

            modelBuilder.Entity("CondominusApi.Models.Condominio", b =>
                {
                    b.Navigation("ApartamentosCond");
                });

            modelBuilder.Entity("CondominusApi.Models.Pessoa", b =>
                {
                    b.Navigation("DependentesPessoa");

                    b.Navigation("PessoaACPessoa");

                    b.Navigation("PessoaNotiPessoa");

                    b.Navigation("UsuarioPessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
